# Generated by Django 4.1.1 on 2022-09-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='prescriber',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
